### ISSUE TITLE
Win10一打开就闪退, 把能关的都关了也无法解决问题,  用ProcessMonitor记录了下崩溃过程

### ISSUE THREAD

**Issue by czy1238677** [OwO-Network/DeepLX#100]
[Logfile.CSV](https://github.com/OwO-Network/DeepLX/files/14736845/Logfile.CSV)

内容有点多, 保存成CSV文件了

**Comment by missuo** [comment]
It should not be double-clicked to open. You must first open Terminal and execute the following command in the directory where the binary file is located.

```bash
.\deeplx_windows_amd64.exe
```

**Comment by czy1238677** [comment]
> It should not be double-clicked to open. You must first open Terminal and execute the following command in the directory where the binary file is located.
> 
> ```shell
> .\deeplx_windows_amd64.exe
> ```
It doesn't work
![QQ截图20240325052900](https://github.com/OwO-Network/DeepLX/assets/9382491/23c71536-6d24-4d80-8d6d-ae6ff43e8468)

**Comment by missuo** [comment]
Since there is no error, it seems that your port is occupied, so the process is killed.

**Comment by czy1238677** [comment]
> Since there is no error, it seems that your port is occupied, so the process is killed.

I have also checked the port, and there is no case of port 1188 being occupied.

![QQ截图20240325053649](https://github.com/OwO-Network/DeepLX/assets/9382491/0a2fb5d5-91a0-4846-9eab-e1ac0f8b6233)

**Comment by missuo** [comment]
I'm sorry I don't have a Windows device to test on.

**Comment by yysuper008** [comment]
我的也是这个问题，闪退，你的解决了吗

**Comment by missuo** [comment]
> 我的也是这个问题，闪退，你的解决了吗

Can you test the [last version](https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.0)?

**Comment by missuo** [comment]
![image](https://github.com/OwO-Network/DeepLX/assets/55200481/2d790382-ea1c-4ebc-af35-63811e8ca365)

I commissioned a friend to test this and was unable to reproduce the problem.

**Comment by czy1238677** [comment]
> 我的也是这个问题，闪退，你的解决了吗

没解决, 我的主力机是win10的, 还有一台win11的电脑里DeepLX可以正常启动,  只能用局域网转发到那台电脑上来使用DeepLX

**Comment by yysuper008** [comment]
我是win11的一直可以运行，但从3月24号就突然打开就闪退。我也弄了两天都不行

**Comment by yysuper008** [comment]
> > 我的也是这个问题，闪退，你的解决了吗
> 
> Can you test the [last version](https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.0)?

I'm using version 0.9.1, but it still doesn't work. It crashes

**Comment by missuo** [comment]
At present, I have not found out the specific reason, but the code of the latest version v0.9.1 has indeed undergone major changes. It is recommended that you use v0.9.0 for the time being. Basically, the experience is the same.

**Comment by yysuper008** [comment]
> At present, I have not found out the specific reason, but the code of the latest version v0.9.1 has indeed undergone major changes. It is recommended that you use v0.9.0 for the time being. Basically, the experience is the same.

The 0.9.0 version also crashes.

**Comment by missuo** [comment]
> > At present, I have not found out the specific reason, but the code of the latest version v0.9.1 has indeed undergone major changes. It is recommended that you use v0.9.0 for the time being. Basically, the experience is the same.
> 
> The 0.9.0 version also crashes.

What about earlier versions? Is it convenient to test it?

**Comment by yysuper008** [comment]
> > > At present, I have not found out the specific reason, but the code of the latest version v0.9.1 has indeed undergone major changes. It is recommended that you use v0.9.0 for the time being. Basically, the experience is the same.
> > 
> > 
> > The 0.9.0 version also crashes.
> 
> What about earlier versions? Is it convenient to test it?


Sure. Convenient. But I've tried many versions already. Still crashing!

**Comment by yysuper008** [comment]
> > > > At present, I have not found out the specific reason, but the code of the latest version v0.9.1 has indeed undergone major changes. It is recommended that you use v0.9.0 for the time being. Basically, the experience is the same.
> > > 
> > > 
> > > The 0.9.0 version also crashes.
> > 
> > 
> > What about earlier versions? Is it convenient to test it?
> 
> Sure. Convenient. But I've tried many versions already. Still crashing!

Is it an issue with the .NET installation?

**Comment by yysuper008** [comment]
> > > At present, I have not found out the specific reason, but the code of the latest version v0.9.1 has indeed undergone major changes. It is recommended that you use v0.9.0 for the time being. Basically, the experience is the same.
> > 
> > 
> > The 0.9.0 version also crashes.
> 
> What about earlier versions? Is it convenient to test it?

Test if it can run normally in Windows Sandbox.

**Comment by ztx6506** [comment]
> ![image](https://private-user-images.githubusercontent.com/55200481/316727011-2d790382-ea1c-4ebc-af35-63811e8ca365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDQ4MTIsIm5iZiI6MTcxMzAwNDUxMiwicGF0aCI6Ii81NTIwMDQ4MS8zMTY3MjcwMTEtMmQ3OTAzODItZWExYy00ZWJjLWFmMzUtNjM4MTFlOGNhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjMwYTIxM2JiZjE5MDcxZjY5OWEwNDYwNWFiY2JlZjI2OTA5MTE4NzZiYzk4ZjNkYjkyOTA2YzI4YTlmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-KabA7KhgEPmuvxvOf1mFU9i88-8dSFrz-Vq4cLpoY)
> 
> I commissioned a friend to test this and was unable to reproduce the problem.
>>i have same problem, v0.9.1 
>>![image](https://github.com/OwO-Network/DeepLX/assets/56108128/bdb81de4-2390-4d42-9d3c-de8f51305d3c)
>>without any error message then exit.
>> my windows version is
>>![image](https://github.com/OwO-Network/DeepLX/assets/56108128/1a4ba395-b142-45f5-ab49-24cbf0365310)
>>I hope the author can fix this bug as early as possible, Thanks!

**Comment by missuo** [comment]
> > ![image](https://private-user-images.githubusercontent.com/55200481/316727011-2d790382-ea1c-4ebc-af35-63811e8ca365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDQ4MTIsIm5iZiI6MTcxMzAwNDUxMiwicGF0aCI6Ii81NTIwMDQ4MS8zMTY3MjcwMTEtMmQ3OTAzODItZWExYy00ZWJjLWFmMzUtNjM4MTFlOGNhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjMwYTIxM2JiZjE5MDcxZjY5OWEwNDYwNWFiY2JlZjI2OTA5MTE4NzZiYzk4ZjNkYjkyOTA2YzI4YTlmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-KabA7KhgEPmuvxvOf1mFU9i88-8dSFrz-Vq4cLpoY)
> > I commissioned a friend to test this and was unable to reproduce the problem.
> > > i have same problem, v0.9.1
> > > ![image](https://private-user-images.githubusercontent.com/56108128/322199471-bdb81de4-2390-4d42-9d3c-de8f51305d3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDU5NDAsIm5iZiI6MTcxMzAwNTY0MCwicGF0aCI6Ii81NjEwODEyOC8zMjIxOTk0NzEtYmRiODFkZTQtMjM5MC00ZDQyLTlkM2MtZGU4ZjUxMzA1ZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OTI0OGMyMjczMzJmODkzODMzZjNjOWRiY2QzM2UxYWYxZTZlZTViNWQ1OGE3Nzc3OTk4MWI0NTdkMzFiNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_3n37jt8w1Go7AkVdbv_udLP7QKK0o5UnQYA5jSZWM)
> > > without any error message then exit.
> > > my windows version is
> > > ![image](https://private-user-images.githubusercontent.com/56108128/322199994-1a4ba395-b142-45f5-ab49-24cbf0365310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDU5NDAsIm5iZiI6MTcxMzAwNTY0MCwicGF0aCI6Ii81NjEwODEyOC8zMjIxOTk5OTQtMWE0YmEzOTUtYjE0Mi00NWY1LWFiNDktMjRjYmYwMzY1MzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNmU3N2NmMGU1NjM1ZWYzMTJiNzhiNzRkNGNiODRmY2U4Mjg4ODAxNTZkY2I4MGRkYjBlYmNkOGRkOWYwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HHrBbOFOBwxPGZNTngVnmH08HN9KvaFp_hoMhZj_YBY)
> > > I hope the author can fix this bug as early as possible, Thanks!

看不到你的图片。

**Comment by ztx6506** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/55200481/316727011-2d790382-ea1c-4ebc-af35-63811e8ca365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDQ4MTIsIm5iZiI6MTcxMzAwNDUxMiwicGF0aCI6Ii81NTIwMDQ4MS8zMTY3MjcwMTEtMmQ3OTAzODItZWExYy00ZWJjLWFmMzUtNjM4MTFlOGNhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjMwYTIxM2JiZjE5MDcxZjY5OWEwNDYwNWFiY2JlZjI2OTA5MTE4NzZiYzk4ZjNkYjkyOTA2YzI4YTlmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-KabA7KhgEPmuvxvOf1mFU9i88-8dSFrz-Vq4cLpoY)
> > > I commissioned a friend to test this and was unable to reproduce the problem.
> > > > i have same problem, v0.9.1
> > > > ![image](https://private-user-images.githubusercontent.com/56108128/322199471-bdb81de4-2390-4d42-9d3c-de8f51305d3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDU5NDAsIm5iZiI6MTcxMzAwNTY0MCwicGF0aCI6Ii81NjEwODEyOC8zMjIxOTk0NzEtYmRiODFkZTQtMjM5MC00ZDQyLTlkM2MtZGU4ZjUxMzA1ZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OTI0OGMyMjczMzJmODkzODMzZjNjOWRiY2QzM2UxYWYxZTZlZTViNWQ1OGE3Nzc3OTk4MWI0NTdkMzFiNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_3n37jt8w1Go7AkVdbv_udLP7QKK0o5UnQYA5jSZWM)
> > > > without any error message then exit.
> > > > my windows version is
> > > > ![image](https://private-user-images.githubusercontent.com/56108128/322199994-1a4ba395-b142-45f5-ab49-24cbf0365310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDU5NDAsIm5iZiI6MTcxMzAwNTY0MCwicGF0aCI6Ii81NjEwODEyOC8zMjIxOTk5OTQtMWE0YmEzOTUtYjE0Mi00NWY1LWFiNDktMjRjYmYwMzY1MzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNmU3N2NmMGU1NjM1ZWYzMTJiNzhiNzRkNGNiODRmY2U4Mjg4ODAxNTZkY2I4MGRkYjBlYmNkOGRkOWYwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HHrBbOFOBwxPGZNTngVnmH08HN9KvaFp_hoMhZj_YBY)
> > > > I hope the author can fix this bug as early as possible, Thanks!
> 
> 看不到你的图片。

>![](https://cdn.jsdelivr.net/gh/ztx6506/resource@master/img/322199994-1a4ba395-b142-45f5-ab49-24cbf0365310.png)
>![](https://cdn.jsdelivr.net/gh/ztx6506/resource@master/img/PixPin_2024-04-13_19-06-18.png)
>这是双击打开录下的gif
>![](https://cdn.jsdelivr.net/gh/ztx6506/resource@master/img/PixPin_2024-04-13_19-04-54.gif)

**Comment by ztx6506** [comment]
换了一台AMD笔记本就行了，系统版本是一样的

**Comment by webnet918** [comment]
的确可能是端口占用的问题，我尝试添加参数-p 手动指定端口，测试成功了。默认1188的端口可能存在冲突或其他未知的问题。感谢作者这么优秀的作品，希望后续能持续更新维护。
