### ISSUE TITLE
沉浸翻译偶尔报错:Unexpected end of JSON input

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [OwO-Network/DeepLX#101]
![image](https://github.com/OwO-Network/DeepLX/assets/62531937/8455fa76-4173-4f52-8d0b-824dde24e178)
rt,docker部署调用沉浸翻译,翻译整个网页内容时最后几段话经常出现下面的报错
![image](https://github.com/OwO-Network/DeepLX/assets/62531937/dd85dfc7-7d2b-4f0f-b5b8-0455f744b977)
刷新重试往往能解决问题,但是比较好奇为什么docker端没有异常
![image](https://github.com/OwO-Network/DeepLX/assets/62531937/eecce6f6-5a21-43f7-9d45-7c0575d2fa1f)

**Comment by missuo** [comment]
[https://github.com/OwO-Network/DeepLX?tab=readme-ov-file#setup-on-immersive-translate](https://github.com/OwO-Network/DeepLX?tab=readme-ov-file#setup-on-immersive-translate)

> It is not recommended, because the immersive-translate will send many requests in a short time, which will cause the DeepL API to block your IP.
