### ISSUE TITLE
the response data is blank

### ISSUE THREAD

**Issue by zsf513** [OwO-Network/DeepLX#102]
![图片](https://github.com/OwO-Network/DeepLX/assets/4221354/8132bb44-2c6b-4479-bab2-5a93c23c81cc)

as the image, the response code is 200, but the data is blank

**Comment by missuo** [comment]
Thanks for feedback. 

https://github.com/OwO-Network/DeepLX/commit/7b97e65ec76e6d56af2ba210a365b2844cbcf571

I have modified the code to avoid the problem of being unable to translate when returning 200.
