### ISSUE TITLE
v2/translate 接口似乎没有校验 token

### ISSUE THREAD

**Issue by tisfeng** [OwO-Network/DeepLX#103]
我部署服务设置了 token，测试 translate 接口确实有校验 token，但 v2/translate 似乎没有 🥲

相关 issue https://github.com/OwO-Network/DeepLX/issues/99

## translate
<img width="594" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/25194972/d442784c-47f7-4771-b1d4-6fc8d1dfce42">

## v2/translate
<img width="581" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/25194972/bf779886-039f-44e8-aa4e-ce0b9bf081b0">

**Comment by missuo** [comment]
Fixed. https://github.com/OwO-Network/DeepLX/commit/15cca97b819756897e788d6d353c7d52e8f4bf1e
