### ISSUE TITLE
M1处理器，执行launchctl start ... 没反应，无法执行。

### ISSUE THREAD

**Issue by cnbiao** [OwO-Network/DeepLX#11]
执行 `launchctl start ~/Library/LaunchAgents/me.missuo.deeplx.plist` 无法启动。

【操作系统】`M1 Pro，MacOS 13.0.1`
【执行程序】`deeplx_darwin_arm64`
【plist文件】`~/Library/LaunchAgents/me.missuo.deeplx.plist`

<img width="757" alt="image" src="https://user-images.githubusercontent.com/13941735/221725300-ff0d691d-7e10-4d50-9e77-887ef1dd3d2c.png">

**Comment by missuo** [comment]
执行完直接用浏览器访问 `http://127.0.0.1:1188` 验证即可，你也可以打开 `Activity Monitor` 搜索是否存在 `deeplx` 的进程。

**Comment by cnbiao** [comment]
没有`deeplx`进程。执行 start 后看终端里红色叉了。

**Comment by missuo** [comment]
请确保你的 `/usr/local/bin` 目录下存在 `deeplx`。你可以使用以下命令验证它是否可以运行。
```bash
cd /usr/local/bin
./deeplx
```

**Comment by cnbiao** [comment]
啊~ 知道问题了，deeplx_darwin_arm64 没有重命名为 deeplx

**Comment by missuo** [comment]
```bash
sudo mv deeplx_darwin_amd64 /usr/local/bin/deeplx
```
可能没有执行这一步。

**Comment by cnbiao** [comment]
是的，。大感谢！ 可以正常使用了！👍🏻
