### ISSUE TITLE
After deployment, a 404 error occurred.

### ISSUE THREAD

**Issue by TiancyWong** [OwO-Network/DeepLX#115]
After deployment, 127.0.0.1:1188 is working:
<img width="1052" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/168951487/e65342dd-3e54-4774-8781-00f387409b2c">
---------
However, 127.0.0.1:1188/translate is not working, I can not find out how to solve it , please help me!
<img width="416" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/168951487/9c88c7d4-54b7-45b9-87b1-08044c10aa66">

**Comment by TiancyWong** [comment]
<img width="1206" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/168951487/bfcca0bf-9487-4143-8475-042591efbb51">

**Comment by missuo** [comment]
You should understand the difference between GET and POST.
