### ISSUE TITLE
DeeplX doest work?

### ISSUE THREAD

**Issue by nimbus2332** [OwO-Network/DeepLX#117]
Hi, is DeeplX no longer working (Docler and WSL)?

After installation and verification, I was able to translate "Hello World" a couple of times, and then all the answers are always 

{"code":503,"message":"DeepL API request failed"}

If you open it http://localhost:1188/translate

it is issued {"code":404,"message":"Path not found"}

At the same time, PyDeepLX is working and accessing ww2 deep, after learning about this, I shared a dynamic mobile proxy so that each python request is sent from a new IP.

**Comment by missuo** [comment]
Your mistake

**Comment by nimbus2332** [comment]
> 我也遇到了这个503错误，上周大概出现了2-3天。之后就正常了。

I don’t know, I bought a Pro account, I also advise you to pay 2$ or 5-20 yuan.
