### ISSUE TITLE
部署到甲骨文首尔和AWS光帆，都提示Too Many Requests，大部分无法翻译，请问卸载命令是？

### ISSUE THREAD

**Issue by geekbb** [OwO-Network/DeepLX#12]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/46196358/221850597-5bea584f-c06d-4676-b2f7-ab7d3a652586.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/46196358/221850608-cdf2e86f-959a-4fdf-aa76-47bc1f9d7a6b.png">

**Comment by missuo** [comment]
是因为你在短时间内发起了太多次请求。

卸载命令如下：
```
systemctl stop deeplx
systemctl disable deeplx
rm -f /etc/systemd/system/deeplx.service
rm -f /usr/bin/deeplx
```
