### ISSUE TITLE
how avoid translation failed, because of empty result ?

### ISSUE THREAD

**Issue by stephanvebrian** [OwO-Network/DeepLX#121]
Hello, i always encounter 503 with message
```json
{
    "code": 503,
    "message": "Translation failed, API returns an empty result."
}
```

how to avoid this ? is premium going to help in this case ?
and is premium really unlimited for translating ? 

i have a batch of text that need to be translated,

thanks..

**Comment by missuo** [comment]
Maybe you can try using the Pro API with `dl_session`.

**Comment by xxxxuanran** [comment]
I have the same issue.
Although the test passed using curl, the Immersive Translate always returned `{"code":503,"message":"Translation failed, API returns an empty result."}`
I am using the `/v1/translate` endpoint and have configured `dl_session`.
![image](https://github.com/OwO-Network/DeepLX/assets/31968665/32ab116d-7175-48e0-899e-12ff51137f8d)
![image](https://github.com/OwO-Network/DeepLX/assets/31968665/40c23560-61f1-4060-8175-10fb2777de97)

**Comment by missuo** [comment]
Perhaps the requests initiated by Immersive Translate are too frequent and the intervals are too short.

**Comment by xxxxuanran** [comment]
> Perhaps the requests initiated by Immersive Translate are too frequent and the intervals are too short.

Thanks for your reply. But that's not the case.
I just clicked `Verify service` once.
![image](https://github.com/OwO-Network/DeepLX/assets/31968665/c4d94de5-30f4-4640-9193-41b07e159075)

This is the log of everything:
![image](https://github.com/OwO-Network/DeepLX/assets/31968665/ff54603d-bf1c-4066-9119-dd6aad17c461)

Could this be an Immersive Translate bug? Likely, sending the wrong header?

**Comment by bropines** [comment]
> Perhaps the requests initiated by Immersive Translate are too frequent and the intervals are too short.
Same Issue
![image](https://github.com/OwO-Network/DeepLX/assets/57861007/339303f2-71ec-47ce-bb8b-7fc4d7dfbd6f)

**Comment by bropines** [comment]
> > Perhaps the requests initiated by Immersive Translate are too frequent and the intervals are too short.
> 
> Same Issue ![image](https://private-user-images.githubusercontent.com/57861007/342860397-339303f2-71ec-47ce-bb8b-7fc4d7dfbd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzkyMzYsIm5iZiI6MTcxOTMzODkzNiwicGF0aCI6Ii81Nzg2MTAwNy8zNDI4NjAzOTctMzM5MzAzZjItNzFlYy00N2NlLWJiOGItN2ZjNGQ3ZGZiZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmRkNzQxMzdlMjI5N2MzZTBmZTA1YjNiNjY2MDc5ZWY3NjE4Y2M4YzQ5MDQ4NWE3NDQwZTYxOTJkY2ZiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kZuNiG5ayjCNFzgI1sVv0Fp98yl0hGMR-uNVjXLUc0c)

No questions, someone just DDoSed me a lot of time

**Comment by stephanvebrian** [comment]
tbh, free tier is very unreliable, you guys should try Pro version, it much better -- never face any issue so far myself
