### ISSUE TITLE
Add to Related Projects

### ISSUE THREAD

**Issue by bropines** [OwO-Network/DeepLX#124]
Is it possible to add a link to my repository? I just copied the logic of [LegendLeo](https://github.com/LegendLeo) onto vercel and overall it seems to work well.

**Comment by missuo** [comment]
Any Link？

**Comment by bropines** [comment]
> Any Link？

Ohhh. Excuse me. Yesterday, when I inserted the github into the markdown, I inserted legendLeo on top of my highlighted link. Here is the link https://github.com/bropines/Deeplx-vercel

**Comment by missuo** [comment]
> Ohhh. Excuse me. Yesterday, when I inserted the github into the markdown, I inserted legendLeo on top of my highlighted link. Here is the link https://github.com/bropines/Deeplx-vercel

Thanks. I'm traveling, I'll check and add this later when I get back to the hotel.

**Comment by bropines** [comment]
You haven't forgotten?

**Comment by missuo** [comment]
> You haven't forgotten?

I'm sorry, I did seem to have forgotten about this, I'll take care of it tonight.

**Comment by missuo** [comment]
added.

https://deeplx.owo.network/related/projects.html
