### ISSUE TITLE
为什么一下载就被查杀了

### ISSUE THREAD

**Issue by hainanashu** [OwO-Network/DeepLX#125]
![微信截图_20240705134244](https://github.com/OwO-Network/DeepLX/assets/25527306/11107851-1908-42da-8713-08b2d124a6a4)

**Comment by hainanashu** [comment]
哈哈哈，只是觉得有点离谱，本人用的是360国际版，非国内版，骂人就有点过分了，只是代码中难免有点...

**Comment by missuo** [comment]
The source code of this project is public, and your current binary is automatically compiled by GitHub Actions. 

**So the only solution is to uninstall 360 Security Guard.**

**Comment by hainanashu** [comment]
老哥越扯越远啊，这不仅骂了我 又骂了运营商，下一步估计到机场主了，我用还不行吗，现在就卸，不影响你们了，谢谢回复
