### ISSUE TITLE
[Feature request] Add an option to listen on a specific ip address instead of 0.0.0.0

### ISSUE THREAD

**Issue by showgood163** [OwO-Network/DeepLX#126]
我用AUR部署了0.9.5版的deeplx的二进制文件而不是docker。

我需要在某个LAN地址非0.0.0.0的地址做listen，但是在deeplx的help字段中没有找到相关选项。

**Comment by missuo** [comment]
Yes, by default it only listens to 0.0.0.0 and does not support modification.
