### ISSUE TITLE
同时使用ipv4和ipv6

### ISSUE THREAD

**Issue by zhengqwe** [OwO-Network/DeepLX#131]
如果系统有ipv6地址的话（一般有两个），就同时用v4和v6一共3个地址，防止429

**Comment by missuo** [comment]
The official API of DeepL does not support IPv6.

**Comment by missuo** [comment]
Have you tested this? Are you sure you are testing in an environment that has no IPv4 network at all?

**Comment by missuo** [comment]
After my test, I cannot access the DeepL API using IPv6.

**Comment by missuo** [comment]
> 2606:4700:22::6815:19d

```json
{
  "code": 503,
  "message": "DeepL API request failed"
}
```
