### ISSUE TITLE
500: {"details":"error: 403","error":"Translation failed"}

### ISSUE THREAD

**Issue by Hyone-soul** [OwO-Network/DeepLX#134]
Dear Administrator

I'm having problems, I'm trying to deploy a DeepLX project on a Linux cloud server and configure the dl_seesion value of my DeepLpro
After deployment, 
I Get request IP/port and the result is as follows
![image](https://github.com/user-attachments/assets/3e130c40-2a68-42f8-8269-c3b7fb4abd4a)

POST request for IP/port/translate with the following result
![image](https://github.com/user-attachments/assets/770a83d9-7dc4-4000-b63e-1d451ac05063)

**What is the reason for this?**

**Comment by Hyone-soul** [comment]
my Port is set 9000

**Comment by missuo** [comment]
**deeplxpro** has nothing to do with this project, and you did not use this project. Thank you.
