### ISSUE TITLE
某些特定词汇返回503？ 比如 announce

### ISSUE THREAD

**Issue by SpiritedAwayLab** [OwO-Network/DeepLX#138]
翻译的句子里 带有 announce  announcement 直接返503
 这是啥奇怪问题

**Comment by SpiritedAwayLab** [comment]
course:#- Advanced Topics in Modeling Health Care Decisions -  也会报错
随机拿走一个 Topics就能不会。。。

**Comment by missuo** [comment]
I tried it and it seems to be caused by your ** :#- **. Just remove it.
