### ISSUE TITLE
Request Parameter 'Text'

### ISSUE THREAD

**Issue by linakima** [OwO-Network/DeepLX#139]
I can't use the [Array[String]](https://developers.deepl.com/docs/api-reference/translate) type in the Text parameter?
When I try to do this, I get the error 400.

I have read your [documentation](https://deeplx.owo.network/endpoints/free.html). It says only String type.
I want to send multiple strings in one request. I could, of course, come up with some kind of separator in this case and pray that Deepl doesn't translate or remove it during processing...

**Comment by missuo** [comment]
Use `\n` pls

**Comment by linakima** [comment]
As a lines separator?
My texts can already use \n for a line break as it is....
