### ISSUE TITLE
why return Invalid target_lang.

### ISSUE THREAD

**Issue by Icedroid** [OwO-Network/DeepLX#140]
I deploy as a docker container, but translate api response:
{"code":-32600,"message":"Invalid Request","data":{"what":"Invalid target_lang."}}

**Comment by missuo** [comment]
**response** already tells you why

**Comment by Icedroid** [comment]
I use it translate english to chinese. Before a week ago It works. how to make it work?

**Comment by missuo** [comment]
read docs.

**Comment by Icedroid** [comment]
I have read docs and I run it with
`docker run -itd -p 1188:1188 ghcr.io/owo-network/deeplx:latest
`
Am I miss something?

**Comment by Icedroid** [comment]
I tunk  back to Bob plugin DeepLX 1.0.8 version. It work. 
So it must  be a bug of new version Bob plugin DeepLX 1.0.9.
