### ISSUE TITLE
503 error on free endpoint

### ISSUE THREAD

**Issue by linakima** [OwO-Network/DeepLX#149]
It always returns 503 Server Error.

```
url = "http://127.0.0.1:1188/translate"
    headers = {
        "Content-Type": "application/json",
        "Authorization": 123
    }
    payload = {
        "text": こんにちは,
        "source_lang": JA,
        "target_lang": EN
    }
```

**Comment by bropines** [comment]
Same error

**Comment by missuo** [comment]
Known bug, please wait for fix.

**Comment by zhonghanwen** [comment]
I'm having the same problem.

**Comment by iwater** [comment]
+1

**Comment by missuo** [comment]
**I have recaptured and analyzed the data. It seems that DeepL has officially stopped the old API.**

I am currently not sure if the new API can be utilized. If I have time, I will try to fix it. Please be patient.

**Comment by Knomo-exe** [comment]
+1

**Comment by zhangyiming748** [comment]
Same error

**Comment by missuo** [comment]
Temporary fix for Free Endpoint, temporarily remove Pro Endpoint.

Reference: [https://github.com/cnbeining/DeepLX-Python](https://github.com/cnbeining/DeepLX-Python). 

Many thanks to **Ning Bei**.

https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.8.1

**Comment by showgood163** [comment]
> Temporary fix for Free Endpoint, temporarily remove Pro Endpoint.
> 
> Reference: https://github.com/cnbeining/DeepLX-Python.
> 
> Many thanks to **Ning Bei**.
> 
> https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.8.1

For now it's working.

**Comment by Patrosi73** [comment]
still returns 503 even with the new update.
![image](https://github.com/user-attachments/assets/96bcb389-4605-48bb-9756-9713334e880c)


https://github.com/cnbeining/DeepLX-Python works but I get rate-limited after about 4 translations

**Comment by missuo** [comment]
I added Pro Endpoint, but it may not actually be functional (available, but no advantage like Free), still needs to be tested and verified.

**Comment by showgood163** [comment]
> I added Pro Endpoint, but it may not actually be functional (available, but no advantage like Free), still needs to be tested and verified.

Version 0.9.8.2 actually breaks the free api. In contrast, version 0.9.8.1 works okay.

**Comment by missuo** [comment]
> > I added Pro Endpoint, but it may not actually be functional (available, but no advantage like Free), still needs to be tested and verified.
> 
> Tested arm64 binary release from GitHub. Version 0.9.8.2 breaks the free api while version 0.9.8.1 works.

What is the specific issue?

**Comment by missuo** [comment]
> > I added Pro Endpoint, but it may not actually be functional (available, but no advantage like Free), still needs to be tested and verified.
> 
> Tested arm64 binary release from GitHub. Version 0.9.8.2 breaks the free api while version 0.9.8.1 works.

Sorry, seems my bad. Already fixed in the next version. https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.8.3

**Comment by showgood163** [comment]
> Sorry, seems my bad. Already fixed in the next version. https://github.com/OwO-Network/DeepLX/releases/tag/v0.9.8.3

The free endpoint in v0.9.8.3 works for now.

**Comment by Owyn** [comment]
`[GIN] 2024/11/07 - 21:27:43 |←[97;41m 503 ←[0m|    480.7874ms |       127.0.0.1 |←[97;46m POST    ←[0m "/translate"
`

same thing with both v0.9.8.3 and v0.9.8.1 win amd 64 - doesn't work

**Comment by Rikj000** [comment]
Hi @missuo, I think it's happening again :thinking:   

I've implemented this package in my [`Git-DeepL-Translator`](https://github.com/Rikj000/Git-DeepL-Translator).
Yesterday it was working fine,   
sometimes it threw 503 errors (due to either Rate Limit or Translation Failed).   

These where fixable by:   
- Rate Limits: Switch VPN connection + restart DeepLX
- Translation Failed: Skip line and continue with next

However today it keeps on throwing 503s, no matter how much I tried above.

I'm using `v0.9.8.3` on Manjaro Linux,    
to install it I've altered the `PKGBUILD` of the currently out of the box outdated `deeplx-bin` as described here:   
https://aur.archlinux.org/packages/deeplx-bin#comment-999642

## Log

### Request
```bash
curl -s -X POST http://localhost:1188/translate \
    -H "Content-Type: application/json" \
    -d "{
    \"text\": \"Bonjour\",
    \"source_lang\": \"FR\",
    \"target_lang\": \"EN\"
}" | jq -r;
```

### Response
```json
{
  "code": 503,
  "message": "Translation failed"
}
```

**Comment by missuo** [comment]
Hi @Rikj000 . The reason why I want to see this situation is that the official has changed the request of the API again.

I'll try to update the code to fix this issue.

**Comment by missuo** [comment]
Thank you for the contribution of @96368a. #161 

The issue has been fixed, please update to v0.9.9.

**Comment by Rikj000** [comment]
Tested and can confirm that `v0.9.9` resolves this issue! :tada:

**Comment by pisceswb** [comment]
The latest version still frequently has 503 errors.
