### ISSUE TITLE
503

### ISSUE THREAD

**Issue by AndreasMarin** [OwO-Network/DeepLX#152]
在使用deeplx_windows_amd64.exe时发现：
```shell
[GIN] 2024/11/03 - 12:59:18 | 503 |    3.0504768s |             ::1 | POST     "/translate"
[GIN] 2024/11/03 - 13:02:25 | 503 |    1.2166269s |             ::1 | POST     "/translate"
``` 
重复下载文件后问题仍然存在，以下是postman测试的raw和response：
```
{
    "text": "Hello World",
    "source_lang":"EN",
    "target_lang":"ZH"
}
``` 
```
{"code":503,"message":"Translation failed, API returns an empty result."}
``` 
最后尝试使用docker部署了一遍发现可以用，那么为什么使用exe返回503呢？

**Comment by missuo** [comment]
I do not have a Windows device for testing, but please note that the binary files for Windows are cross-compiled and generated by Go, so theoretically they should be the same.
