### ISSUE TITLE
bob导入失败

### ISSUE THREAD

**Issue by Skylush** [OwO-Network/DeepLX#157]
看着有支持bobplugin为什么无法到，找不到.bobplugin文件
<img width="991" alt="image" src="https://github.com/user-attachments/assets/eec4b303-150a-45a8-aafc-804695e4ff52">
<img width="749" alt="image" src="https://github.com/user-attachments/assets/170f7e55-8f64-4030-b0f0-a053a691e12d">

**Comment by missuo** [comment]
Pls read the docs carefully.
