### ISSUE TITLE
如何获得沉浸式翻译的URL | How to get the URL of an immersive translation

### ISSUE THREAD

**Issue by leegx1998** [OwO-Network/DeepLX#16]
Windows谷歌浏览器 
已经安装了沉浸式翻译插件
打开开发者模式后，无法获得URL
![image](https://user-images.githubusercontent.com/69112231/222312332-205aa5f9-c26e-47a4-a7d9-17343ffe3dd7.png)

**Comment by missuo** [comment]
url是你部署完这个项目之后的api。

**Comment by kwekewk** [comment]
> url is the api after you deploy the project.

error 405?
![image](https://user-images.githubusercontent.com/101484315/223223942-2157279e-d175-4d15-aa62-5295a1d14c6b.png)

![image](https://user-images.githubusercontent.com/101484315/223224215-3b3c4825-5816-4936-a421-54d7fb2c9e08.png)

**Comment by missuo** [comment]
> > url is the api after you deploy the project.
> 
> error 405? ![image](https://user-images.githubusercontent.com/101484315/223223942-2157279e-d175-4d15-aa62-5295a1d14c6b.png)
> 
> ![image](https://user-images.githubusercontent.com/101484315/223224215-3b3c4825-5816-4936-a421-54d7fb2c9e08.png)

Maybe you should understand what listening at 0.0.0.0 means. You should fill in the API URL at `http://[IP]:1188/translate`. If you deploy locally on your computer, the IP should be 127.0.0.1 or localhost.
