### ISSUE TITLE
The 503 error

### ISSUE THREAD

**Issue by bobo-wangyan** [OwO-Network/DeepLX#160]
The 503 error appeared again. It was still possible to request yesterday. I am using the free mode. Has the API changed again?
{
    "code": 503,
    "message": "Translation failed"
}

**Comment by Gol2dragon** [comment]
same problem as yours

**Comment by lurudong** [comment]
same problem as yours

**Comment by MRchenao** [comment]
same errors

**Comment by Rikj000** [comment]
Duplicate of #149

**Comment by missuo** [comment]
Thank you for the contribution of @96368a. #161 

The issue has been fixed, please update to v0.9.9.
