### ISSUE TITLE
Will you consider supporting brew installation?

### ISSUE THREAD

**Issue by lonelygo** [OwO-Network/DeepLX#17]
Using brew to install and update will be more user friendly.

**Comment by missuo** [comment]
I'm also an avid fan of Brew, but I don't know if it's possible. I will try it sometime.

**Comment by missuo** [comment]
It is already supported, you can try it out and let me know if you encounter any problems, thanks. @lonelygo 

[Install with Homebrew](https://github.com/OwO-Network/DeepLX/blob/main/README.md#homebrew)

**Comment by lonelygo** [comment]
> It is already supported, you can try it out and let me know if you encounter any problems, thanks. @lonelygo
> 
> [Install with Homebrew](https://github.com/OwO-Network/DeepLX/blob/main/README.md?rgh-link-date=2023-03-02T03%3A53%3A27Z#homebrew)

@missuo It's awesome work 👍. I've replaced the manual installation with Homebrew and everything seems to be working fine so far.
