### ISSUE TITLE
CLI 直接运行，提示 404

### ISSUE THREAD

**Issue by w316525096** [OwO-Network/DeepLX#22]
OS：debian 11
脚本安装失败后，下载安装包直接运行提示 404。
如图：
![image](https://user-images.githubusercontent.com/25398881/222650593-68f274c5-59fc-4b40-9293-4df5a3b779a6.png)

**Comment by missuo** [comment]
请注意当你访问 /translate 的时候需要POST请求，当你访问 / 的时候仅支持GET请求。谢谢。

**Comment by w316525096** [comment]
![image](https://user-images.githubusercontent.com/25398881/222651680-9b855508-3c49-40f7-806e-a6c6c8dd0af7.png)

多谢回复，打扰了。
