### ISSUE TITLE
Docker部署

### ISSUE THREAD

**Issue by alegoho** [OwO-Network/DeepLX#25]
我Docker上部署完后打不到，请问是什么问题？

**Comment by missuo** [comment]
不太明白

**Comment by alegoho** [comment]
Backup the Docker Image of zu1k
docker run -itd -p 1188:80 missuo/deeplx-bk

**Comment by missuo** [comment]
I don't understand what the problem is that you are experiencing.

**Comment by alegoho** [comment]
> I don't understand what the problem is that you are experiencing.

Setup on Docker

**Comment by missuo** [comment]
If you reply in this way again, I won't be able to respond to this issue. At what step did you encounter the problem? Otherwise, I can't answer your question.

**Comment by alegoho** [comment]
> If you reply in this way again, I won't be able to respond to this issue. At what step did you encounter the problem? Otherwise, I can't answer your question.如果你再这样回复，我就无法回应这个问题了。您在哪一步遇到了问题？否则，我无法回答你的问题。

我在Docker 上部署了，但我部署完打不开

还有我在VPS上也部署了，URL也填了，测试显示404

root@localhost:~# bash <(curl -Ls https://cpp.li/deeplx)
DeepLX latest version: v0.7.4, Start install...
Created symlink /etc/systemd/system/multi-user.target.wants/deeplx.service → /etc/systemd/system/deeplx.service.
Installed successfully, listening at 0.0.0.0:1188
root@localhost:~# deeplx
DeepL X has been successfully launched! Listening on 0.0.0.0:1188
Made by sjlleo and missuo.

**Comment by missuo** [comment]
请提供你的URL，以及404的截图。

**Comment by alegoho** [comment]
> 请提供你的URL，以及404的截图。

我用沉浸式翻译，请问那个URL是VPS的地址加上端口吗？

**Comment by missuo** [comment]
> 

不是，请你仔细阅读README，再来提问，谢谢。

**Comment by alegoho** [comment]
> > 
> 
> 不是，请你仔细阅读README，再来提问，谢谢。

刚才加去看了README，就看MAC那图我才看到后面要加/translate

**Comment by alegoho** [comment]
> Member

还有一个问题，支持arm64吗？在ARMBIAN上安装行不行？

**Comment by CooperHash** [comment]
> > Member
> 
> 还有一个问题，支持arm64吗？在ARMBIAN上安装行不行？

作者耐心的回复了好多次，重复告诉你去先好好看Readme，提供相应截图和error提示，你仔细看看你回复了什么，你代表了很多类似的这样“伸手党”的国内开发者，不断的恶化美好的开源社区，不断的透支开源开发者的奉献意愿
