### ISSUE TITLE
添加 CORS

### ISSUE THREAD

**Issue by K024** [OwO-Network/DeepLX#27]
可以添加 CORS headers 以允许浏览器插件或者 SPA 直接访问。`http://localhost:<port>` 是 [potentially trustworthy origin](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy)，可以直接从 https 的 origin 访问。

[Gin CORS 中间件](https://github.com/gin-contrib/cors)

```go
func main() {
  router := gin.Default()
  // same as
  // config := cors.DefaultConfig()
  // config.AllowAllOrigins = true
  // router.Use(cors.New(config))
  router.Use(cors.Default())
  router.Run()
}
```

**Comment by missuo** [comment]
You can submit a PR directly to the main branch and I will approve the merge.
