### ISSUE TITLE
根据release更新docker镜像

### ISSUE THREAD

**Issue by yyysuo** [OwO-Network/DeepLX#29]
您好，感谢您的杰出工作。我用docker版本部署了服务，用起来很爽，可以用您发布的版本去更新docker版本的服务吗？我用amd64版本的二进制文件替换了docker中根目录的deepl文件，发现并不能生效，服务不能使用了。

**Comment by missuo** [comment]
您好，我不太明白您的意思，Docker版本是个Image，您所说的“docker中根目录”是什么？

**Comment by yyysuo** [comment]
> 您好，我不太明白您的意思，Docker版本是个Image，您所说的“docker中根目录”是什么？

![image](https://user-images.githubusercontent.com/10081071/223193939-838b4ce4-4e6f-4062-8179-d59fa73fc8f4.png)

**Comment by yyysuo** [comment]
我先在portainer ui中通过sh rm -rf deepl，然后在主机中docker cp /mnt/sda3/deepl deeplx:deepl ，复制下载并解压后的二进制文件到docker，完成对deepl文件的替换，但是这样并不生效。

**Comment by missuo** [comment]
很抱歉，你不能这么做。使用Release中的二进制直接运行和使用Docker镜像是两种不同的部署方式，我建议你选择其中一种。

如果你想使用Release中的二进制部署，我提供了一键脚本。
如果你使用Docker部署，请直接拉取ghcr的最新镜像。

**Comment by yyysuo** [comment]
> 很抱歉，你不能这么做。使用Release中的二进制直接运行和使用Docker镜像是两种不同的部署方式，我建议你选择其中一种。
> 
> 如果你想使用Release中的二进制部署，我提供了一键脚本。 如果你使用Docker部署，请直接拉取ghcr的最新镜像。

感谢您的回复，请问有链接吗？

**Comment by missuo** [comment]
我现在正在支持Dockerhub，请稍等。

**Comment by yyysuo** [comment]
用起来很棒，谢谢。
