### ISSUE TITLE
429 too many request

### ISSUE THREAD

**Issue by yyysuo** [OwO-Network/DeepLX#30]
访问如下网页整页翻译时，报标题中错误。

![image](https://user-images.githubusercontent.com/10081071/223277508-4a663c2d-1a9d-4b18-8b69-9f4262059fdd.png)

**Comment by yyysuo** [comment]
https://www.nytimes.com/2023/03/06/world/middleeast/israel-military-judiciary.html

**Comment by missuo** [comment]
Please read the README carefully. this is not a problem with our program. Thank you.
