### ISSUE TITLE
[Question] Does any Windows desktop application support DeepLX (self-hosted DeepL API)?

### ISSUE THREAD

**Issue by GrayXu** [OwO-Network/DeepLX#31]

**Comment by missuo** [comment]
Gray. I am sorry because I hardly use Windows normally, I know there is an app similar to Bob called biyi, but I don't know if it is still available, maybe it can support self-hosted API, you can try it.

**Comment by missuo** [comment]
https://github.com/biyidev/biyi

**Comment by GrayXu** [comment]
Thank you for your response! However, it appears that Biyi only supports the use of an official DeepL key 😢.

**Comment by missuo** [comment]
I don't know if biyi can support the installation of plugins, perhaps a plugin can be written to support DeepL's self-host API.

**Comment by GrayXu** [comment]
I also tried searching for similar Windows software before, but unfortunately I found nothing. Biyi does have a relatively modern interface and design, and it has separated the implementation of the translation engine. However, it seems that this project is no longer being maintained. 

I am not very familiar with Flutter, but I will see if I can make any relevant modifications.

Thanks!

**Comment by missuo** [comment]
https://github.com/zu1k/translator

Forgot to recommend it to you! You can check out this project, zu1k has Free DeepL built in.
