### ISSUE TITLE
[ mac m1] brew services start owo-network/brew/deeplx  failed

### ISSUE THREAD

**Issue by pfzhan** [OwO-Network/DeepLX#35]
(base) ➜  ~ brew services start owo-network/brew/deeplx

Error: uninitialized constant Homebrew::Service::System
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:61:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by pfzhan** [comment]
my brew vesion
Homebrew 4.0.11
Homebrew/homebrew-core (git revision 1228a3680c6; last commit 2022-12-13)
Homebrew/homebrew-cask (git revision 931327df1f; last commit 2023-03-31)

**Comment by missuo** [comment]
Sorry, I'm using the same version of Homebrew as you and also have an M1 device. Unable to reproduce your problem, please reinstall and retry, or reinstall Homebrew.
