### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by killo3967** [OwO-Network/DeepLX#36]
Could you compile your proyect to Windows binary 32/64? I could install it as a service using NSSM.

I think is very interesting because i am using a plugin for Calibre for translate books and there is a issue for this theme.

https://github.com/bookfere/Ebook-Translator-Calibre-Plugin/issues/6

The problem is that Windows users will be orphaned without your binary windows version.

**Comment by missuo** [comment]
I remember I compiled the Windows binary.
