### ISSUE TITLE
Formal and informal

### ISSUE THREAD

**Issue by adocampo** [OwO-Network/DeepLX#38]
I would like to choose when to use formal or informal tone in those languages supporting those tones. Now it mixes those styles in the translation.

I know this is a feautre on DeepL Pro, but I would like to know if it can be done with DeepLX somehow.

Thank you.

**Comment by missuo** [comment]
Unfortunately, it seems that this is not possible. This is because the project uses the same API as the DeepL web side and the DeepL iOS/Android client. As far as I know, this is not possible on the client side or the web side. @adocampo

**Comment by adocampo** [comment]
Ok, good to know. 
Thank you anyway.
