### ISSUE TITLE
error code 429 Too Many Requests

### ISSUE THREAD

**Issue by adocampo** [OwO-Network/DeepLX#39]
I wrote a program to translate SRT subtitle files, translating the input file line by line, but unfortunately I reached the free usage limit on DeepL not even finishing my first subtitle :P

I know this is not related to DeepLX, but the description misleaded me by saying: "deeplx is unlimited to the number of requests.", perhaps deeplx is unilimited, but as it has deepl as its backend, it has, in fact, limit for requests.

I've searched on the DeepL website and I didn't found the requests limit anywhere, but clearle it has one.
![image](https://user-images.githubusercontent.com/2266612/232481606-3a42402b-d32c-4ae6-996e-958dda73448d.png)

**Comment by missuo** [comment]
What I can tell you is that this project doesn't do any restrictions in the code. But unfortunately, the official API of DeepL may have done some protection, and to avoid 429 such a situation, I suggest to add a sleep after each request, maybe it will work well. @adocampo

**Comment by sandyplus** [comment]
@missuo How to add a sleep for each request?
Best regards.
Sandy

**Comment by missuo** [comment]
> @missuo How to add a sleep for each request?
> 
> Best regards.
> 
> Sandy
> 
> 
> 
> 

Python
```python
import time
time.sleep()
```
