### ISSUE TITLE
In the function getTimeStamp in the calculation of i_count need to +1

### ISSUE THREAD

**Issue by akl7777777** [OwO-Network/DeepLX#4]
In the function getTimeStamp in the calculation of i_count need to +1, because I download the code in the local start often reported too many requests, by checking the web version of deepl source code, found that the initial value of i_count should be 1, and then the statistics need to translate the text of the character "i The number of "i" in the text to be translated, with this total number plus 1 is the way to calculate the timestamp; I added this line of code and then recompiled without this problem.

![0f16893c0a0e3af878580d6928ce39f3](https://user-images.githubusercontent.com/84266551/219520421-87aff087-9e63-4f74-a3b9-2850f235f0c1.png)

**Comment by missuo** [comment]
I did encounter the problem of `too many requests`. Thank you for correcting it. I will recompile and test it immediately.

**Comment by missuo** [comment]
```json
{"code":-32600,"message":"Invalid Request","data":{"what":"Invalid regionalVariant for non-english target language."}}
```

new error.
