### ISSUE TITLE
api return 403？

### ISSUE THREAD

**Issue by ilovebody** [OwO-Network/DeepLX#42]
how to solve pls？

**Comment by missuo** [comment]
Is it possible to provide me with screenshots, I need to check the parameters you passed.

**Comment by freedly2023** [comment]
直接访问提示：{"code":200,"message":"DeepL Free API, Made by sjlleo and missuo. Go to /translate with POST. http://github.com/OwO-Network/DeepLX"}
加上/tranlate 测试是403，你看看需要我截图哪里

**Comment by missuo** [comment]
**translate** 拼错了，另外只接受 POST 请求！

**Comment by freedly2023** [comment]
抱歉，是拼错是我回复时弄错了。真实是对的。
<img width="850" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/128773290/c4b37c25-5cf3-4457-9707-9877f09a9c78">
<img width="1040" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/128773290/a34bfdfd-eab7-49df-b06a-09044b8491fb">

**Comment by missuo** [comment]
我注意到你的日志显示的是 GET 请求，请注意只能接受 POST。

**Comment by freedly2023** [comment]
谢谢您的耐心，我特别渴望调试成功。
这是我第一次使用docker，我是直接在里面搜索找到了。
<img width="1138" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/128773290/7635247d-d9af-4db3-adbd-047809c65a6a">
如果这个版本不对的话，应该是哪个呢，或者说应该下载哪个呢。
