### ISSUE TITLE
Interoperability support

### ISSUE THREAD

**Issue by Saiv46** [OwO-Network/DeepLX#43]
Currently API is incompatible with neither DeepL nor Libretranslate one.

**DeepL API**: Uses FormData as body, also all paths starts with `/v2/`
```http
POST /v2/translate HTTP/2
Content-Type: application/x-www-form-urlencoded

text=Hello%2C%20world!&target_lang=DE
```
```http
200 OK
Content-Type: application/json

{
  "translations": [
    {
      "detected_source_language": "EN",
      "text": "Hallo, Welt!"
    }
  ]
}
```

---

**Libretranslate API**: Have other parameter names
```http
POST /translate HTTP/2
Content-Type: application/json

{
    q: "Hello world!",
    source: "auto",
    target: "de"
}
```
```http
200 OK
Content-Type: application/json

{
    "detectedLanguage": {
        "confidence": 92,
        "language": "en"
    },
    "translatedText": "Hallo Welt!"
}
```

**Comment by missuo** [comment]
I want to know why I want to be compatible. This project is completely independent. If you want the API of this project to be available on other applications, all that needs to be done is for the application to be compatible with DeepLX.
