### ISSUE TITLE
Autodetect language

### ISSUE THREAD

**Issue by Bloeckchengrafik** [OwO-Network/DeepLX#44]
Would it be possible to use deepl's auto-detect language api for translation?

**Comment by missuo** [comment]
We are now using a library of Golang to automatically judge the language. As far as I know, DeepL does not provide an open language detection API.

**Comment by Bloeckchengrafik** [comment]
Thanks for the quick answer. How is that library called?

**Comment by missuo** [comment]
"github.com/abadojack/whatlanggo"
