### ISSUE TITLE
429 error even though it was my first time, I can use site's translation.

### ISSUE THREAD

**Issue by toprak** [OwO-Network/DeepLX#45]
It was my first time, and I just tried this ```[tbb@hai ~]$ curl -d '{"text":"hello", "source_lang":"EN", "target_lang":"DE"}' -H "Content-Type: application/json" -X POST 0.0.0.0:1188/translate
{"code":429,"message":"Too Many Requests"}[tbb@hai ~]$ curl -d '{"text":"hello", "source_lang":"EN", "target_lang":"DE"}' -H "Content-Type: application/json" -X POST 0.0.0.0:1188/translate```

**Comment by missuo** [comment]
It could be that your IP has been blocked before, which is beyond my control. 

**You can try again using Proxy. **

Thank you.
