### ISSUE TITLE
Request to add multi-IP proxy

### ISSUE THREAD

**Issue by cgapk123** [OwO-Network/DeepLX#47]
Due to the long request, HTTP 429 error occurs, can you add and integrate multiple ip proxies in deeplx_windows_amd64.exe?

Related projects: https://github.com/HaliComing/fpp

**Comment by missuo** [comment]
Using a proxy pool is indeed a good suggestion. However, due to the limited IP of the proxy pool, if the program has a built-in proxy pool, these IPs will be blocked soon, so I still prefer to leave the proxy to the user.

**Comment by toprak** [comment]
it would be good though
