### ISSUE TITLE
post method return 404

### ISSUE THREAD

**Issue by kscale** [OwO-Network/DeepLX#48]
`http://123.207.59.59:8100/translate/?"text"= "Hello World"&"source_lang"= "EN"&"target_lang"= "ZH"`

{"code":404,"message":"No Translate Text Found"}

get method works.

**Comment by missuo** [comment]
You should probably learn how to initiate GET/POST requests.

**Comment by missuo** [comment]
BTW, I want to tell you that the project I wrote only supports POST requests.
