### ISSUE TITLE
运行命令时出错

### ISSUE THREAD

**Issue by columbine2k** [OwO-Network/DeepLX#5]
**问题:**
当我运行"launchctl load /Library/LaunchAgents/me.missuo.deeplx.plist"时，
终端输出:
`Load failed: 5: Input/output error`
`Try running `launchctl bootstrap` as root for richer errors.`
**平台:m2 mac**

**Comment by missuo** [comment]
> **问题:** 当我运行"launchctl load /Library/LaunchAgents/me.missuo.deeplx.plist"时， 终端输出: `Load failed: 5: Input/output error` `Try running `launchctl bootstrap` as root for richer errors.` **平台:m2 mac**

目录不对

**Comment by columbine2k** [comment]
感谢，问题已解决。
