### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by missuo** [OwO-Network/DeepLX#51]
DeepL may have updated the API logic, which may trigger an unusable situation at present. 

Wait for the next version of DeepLX to be released.

**Comment by devjia** [comment]
always get response:

**Comment by sk163** [comment]
遇到未知错误，状态码：200

**Comment by luoqisheng** [comment]
这个问题是必现的吗，我这好像没有问题

**Comment by cehnhy** [comment]
request.Header.Set("Accept-Encoding", "gzip, deflate, br")

http.response.Content-Encoding=br

Need to support decompression

**Comment by missuo** [comment]
> request.Header.Set("Accept-Encoding", "gzip, deflate, br")
> 
> 
> 
> http.response.Content-Encoding=br
> 
> 
> 
> Need to support decompression

Thanks for the information.

**Comment by missuo** [comment]
Fixed, please wait for [0.8.0](https://github.com/OwO-Network/DeepLX/releases/tag/v0.8.0) to finish compiling.

**Comment by sk163** [comment]
> Fixed, please wait for [0.8.0](https://github.com/OwO-Network/DeepLX/releases/tag/v0.8.0) to finish compiling.

已经更新到0.8.0版本，使用bob请求依然报：遇到未知错误，状态码：200

**Comment by toprak** [comment]
@missuo I do not know did you update docker but it still gives same error on my end with latest docker image, thanks.

**Comment by missuo** [comment]
> I do not know did you update docker but it still gives same error on my end with latest docker image, thanks.

Of course, Docker has been updated, please delete the old image, restart and try again.
