### ISSUE TITLE
插件未返回有效结果

### ISSUE THREAD

**Issue by leeyyl** [OwO-Network/DeepLX#52]
macOS Ventura 13.4
deeplx service version: 0.7.8
DeepL X 插件：1.0.5

<img width="395" alt="CleanShot 2023-06-29 at 17 43 44@2x" src="https://github.com/OwO-Network/DeepLX/assets/1969512/13214bf0-8cfb-4e7b-982f-99717e991e2a">

**Comment by BoyanXu** [comment]
Same situation.

**Comment by justmd5** [comment]
> Same situation.

+1

**Comment by 821869798** [comment]
+1

**Comment by KevinYouu** [comment]
The same problem

**Comment by missuo** [comment]
Sorry for being away recently, I will release a new version when I get home tomorrow or the day after tomorrow.

**Comment by missuo** [comment]
Fixed, please wait for (0.8.0)[https://github.com/OwO-Network/DeepLX/releases/tag/v0.8.0] to finish compiling.
