### ISSUE TITLE
是否能支持一次性翻译多个句子

### ISSUE THREAD

**Issue by luoqisheng** [OwO-Network/DeepLX#57]
有多个句子需要一次性翻译，如果逐句翻译的话，容易429被封，是否能支持一次请求翻译多个句子

**Comment by missuo** [comment]
The API design of DeepLX supports translation of multiple sentences, even a long paragraph, but unfortunately, the immersive translation plug-in disassembles each paragraph and frequently initiates multiple requests in a short period of time, which will result in 429 However, please note that the risk control of 429 cannot be determined by DeepLX.

Recommended for use with Bob.

**Comment by luoqisheng** [comment]
我的意思是，我看代码里是能 传入texts数组的，但是在计算icount的时候，假定了只有一个text。 是否可以接受texts 数组进行翻译，输出结果以map的方式

**Comment by missuo** [comment]
> 我的意思是，我看代码里是能 传入texts数组的，但是在计算icount的时候，假定了只有一个text。 是否可以接受texts 数组进行翻译，输出结果以map的方式

The implementation of this project is achieved by capturing packets on the DeepL client and simulating client requests. I tried to translate different content on the client, and I found that there is always only one text in the texts array of the client, so I am not sure whether it can be passed in A lot of text.
