### ISSUE TITLE
Make it usable as a library

### ISSUE THREAD

**Issue by gi-yt** [OwO-Network/DeepLX#58]
It would be great if I can directly use this as a library instead of having this as an extra server that has to be run separately

**Comment by missuo** [comment]
I think it is achievable, I have provided a Python version of the library, Golang's library is coming, stay tuned, I don't think it will be long.

Thanks for suggestions.

@gi-yt

**Comment by missuo** [comment]
Done.

[https://github.com/OwO-Network/gdeeplx](https://github.com/OwO-Network/gdeeplx)

**Comment by gi-yt** [comment]
@missuo saw that gdeeplx got deprecated, is there any alternative I can migrate to?

**Comment by missuo** [comment]
Pls reed docs.

**Comment by gi-yt** [comment]
Ah right, I'll update my application to use github.com/OwO-Network/DeepLX/translate in that case.

Thanks!
