### ISSUE TITLE
Windows+Zotero应该如何进行配置

### ISSUE THREAD

**Issue by VioletVia** [OwO-Network/DeepLX#59]
您好，我想在Windows电脑上Zotero里面输入密钥配置deepl进行翻译，您的教程我没有太看懂，Windows具体应该下载哪一个文件（最新版两个Windows文件无法下载，浏览器会提示不安全），不知道您方不方便给一个Windows的配置教程，非常感谢

**Comment by missuo** [comment]
浏览器显示不安全请更换浏览器，所有的版本都是通过 GitHub Action 自动编译的。
