### ISSUE TITLE
插件运行原理

### ISSUE THREAD

**Issue by Boris3305** [OwO-Network/DeepLX#6]
这个插件运行还是要用docker安装服务器才行是吗。还是说我自己操作有问题，他其实已经把服务器部署到本地了？

**Comment by missuo** [comment]
您好，Docker版本不是我维护的，只是对zu1k的做了备份。

目前您如果运行在Mac上，仅需要按照步骤部署即可，不需要Docker。

如果您部署在服务器上，请直接使用一键命令。

Mac上判断是否已经运行，可以使用在资源管理器，搜索deeplx。

**Comment by Boris3305** [comment]
我确实是一步一步按照说明来的，我的电脑是2015款macbook，系统是13.4

下载darwin_amd_64的包移动到/usr/local/bin/deeplx
然后再用户~/lab 下载list
最后LOAD 和 START

资源管理器里没有deeplx不知道啥原因

**Comment by missuo** [comment]
请确保 /usr/local/bin/ 目录下存在deeplx的二进制文件。

**Comment by Boris3305** [comment]
ls /usr/local/bin 
autopoint			git-shell			msginit
brew				git-upload-pack			msgmerge
com.docker.cli			gitk				msgunfmt
deeplx				hub-tool			msguniq

确认过存在deeplx文件，而且我全部删除重新走了遍流程，难道需要重启电脑才行吗

**Comment by missuo** [comment]
@Boris3305 你直接在Teminal执行， `deeplx` 试试看

**Comment by Boris3305** [comment]
搞了半天发现是权限给的不够，人麻了。
麻烦你啦

**Comment by missuo** [comment]
> 搞了半天发现是权限给的不够，人麻了。 麻烦你啦

```
sudo chmod +x /usr/local/bin/deeplx
```
