### ISSUE TITLE
[功能请求] 添加代理参数 (已知PyDeepLX有代理选项)

### ISSUE THREAD

**Issue by photkey** [OwO-Network/DeepLX#63]
使用这个[sing-box ](https://github.com/qjebbs/sing-box/blob/main/docs/configuration/outbound/loadbalance.zh.md) 可以把机场订阅自建成代理ip池，类似于爬虫用的隧道代理，效果如下图：

![image](https://github.com/OwO-Network/DeepLX/assets/60434581/4f6ec3d1-4722-4895-ad00-d4b0f931f388)
只要设置一个代理就可以了，这样的话 在immersive-translate上应该就可以正常使用了。

**Comment by missuo** [comment]
I think the IP load balancing these go on the proxy app, not DeepLX.

**Comment by missuo** [comment]
**Because it is currently running properly!**

The proxy option cannot solve the problem of frequent 429 requests because you need a large IP pool.

If you feel necessary, you can submit a PR. Due to academic pressure, I will not add any more features unless it is to fix some bugs.

Thanks!
