### ISSUE TITLE
returns source_lang from result

### ISSUE THREAD

**Issue by aeongdesu** [OwO-Network/DeepLX#64]
server detects source lang if there is no `source_lang` param: https://github.com/OwO-Network/DeepLX/blob/main/main.go#L155
But It's not possible how to get what language the server detected from the results.
It would be nice to have a return source lang from result.

**Comment by missuo** [comment]
This is easy to do. Next version I will consider returning the source and target languages.

**Comment by missuo** [comment]
Done. Please wait for the Github Action to compile [v0.8.1](https://github.com/OwO-Network/DeepLX/releases/tag/v0.8.1).
