### ISSUE TITLE
Cannot run the released version in win11.

### ISSUE THREAD

**Issue by LASTsue** [OwO-Network/DeepLX#75]
Cannot run the released version in win11.

**Comment by missuo** [comment]
show me the error message.

**Comment by redworkcomtr** [comment]
There is no answer.
<img width="488" alt="image" src="https://github.com/OwO-Network/DeepLX/assets/81250303/371a73e6-7505-43a5-9b37-c0d9a6453b47">

**Comment by missuo** [comment]
Because you didn't specify the `source language`, it was mistakenly identified as `NL`.

pls add parameter **source_lang**.

**Comment by missuo** [comment]
> There is no answer. <img alt="image" width="488" src="https://private-user-images.githubusercontent.com/81250303/286750229-371a73e6-7505-43a5-9b37-c0d9a6453b47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyOTUyODgsIm5iZiI6MTcwMTI5NDk4OCwicGF0aCI6Ii84MTI1MDMwMy8yODY3NTAyMjktMzcxYTczZTYtNzUwNS00M2E1LTliMzctYzBkOWE2NDUzYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDIxNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZmZmNDc1Nzg2MDE4NjkwMjkxYmQwN2MxOGQyZDE1NDhhNWVmOWM3Y2Y3Njk5ZGM2MDgyODUyMzIwNmE3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4egdTsImhjTFmZvjvs3IzNbnpfOPte12TC1vIn8ViRs">

#76

**Comment by missuo** [comment]
It has been restored. @redworkcomtr
