### ISSUE TITLE
[Urgent] Known Bug

### ISSUE THREAD

**Issue by missuo** [OwO-Network/DeepLX#76]
**Earlier today, all APIs dependent on this project were unable to return any translation results. It is possible that DeepL officials made some changes, but I am not sure yet. I will do my best to fix this issue as soon as possible.**

**Comment by missuo** [comment]
It seems that the DeepL API server is experiencing an issue.

![c016f591280e38fda45f2](https://missuo.ru/file/c016f591280e38fda45f2.jpg)

**Comment by missuo** [comment]
It has been restored.

**Comment by yuejunzhang** [comment]
> > But the API https://api.deeplx.org/translate
> > cannot return the translation result properly
> 
> This API may not use DeepLX.

Are there any other free translation APIs available? thanks
