### ISSUE TITLE
沉浸式翻译的API URL如何添加TOKEN？

### ISSUE THREAD

**Issue by wekingchen** [OwO-Network/DeepLX#77]
使用 Docker 运行时，添加了TOKEN参数，请问在沉浸式翻译的API URL里，应该以怎样的格式把TOKEN添加进去呢？直接填写这样的URL不能用https://api.deeplx.org/translate，谢谢！

**Comment by missuo** [comment]
**TOKEN** is currently not supported in 沉浸式翻译.

**Comment by wekingchen** [comment]
明白了，谢谢
