### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by AjianYo** [OwO-Network/DeepLX#8]
macOS bob社区版 bob插件，配置好后总是提示：配置遇到未知错误，状态码：undefined

**Comment by missuo** [comment]
> macOS bob社区版 bob插件，配置好后总是提示：配置遇到未知错误，状态码：undefined

请提供配置截图，以及报错截图谢谢。

**Comment by missuo** [comment]
@AjianYo 很抱歉我目前使用的是商店版，据我所知，从社区版到商店版，`DeepLX`插件是一直没有改过的。请确保您的API部署正确。
