### ISSUE TITLE
Feature: support "tag_handling": "html"

### ISSUE THREAD

**Issue by wisetonny** [OwO-Network/DeepLX#83]
To translate text with HTML tags, such as:

```
<p>The Four Laws are: </p>\n\n<ul>\n<li><strong>Make it obvious</strong></li>\n<li><strong>Make it attractive</strong></li>\n</ul>\n\n<p>These are based on the four steps of the habit loop: cue, craving, response, and reward.</p>\n
```

https://www.deepl.com/docs-api/translate-text/translate-text

**Comment by missuo** [comment]
If you want to implement this feature, you are welcome to submit a PR. **Because this project is based on the DeepL iOS App, this feature is currently not supported.**

**Comment by wisetonny** [comment]
I am not familiar with how to compile and test this library. Here are a few tips we may try:

1. Add the tag_handling somewhere in translateByAPI, it should be in the payload.

The https://api-free.deepl.com/v2/translate supports the `"tag_handling": "html"` based on an API call to DeepL.

It should be able to handle HTML tags, and there is no need to try step 2.

2. Add an option for Splitting: nonewlines (default when tag_handling=html) - splits on punctuation only, ignoring newlines.

It's the code in this lib:

```go
Params: Params{
			Splitting: "newlines",
...
}
```

**Comment by missuo** [comment]
Please note: These are two completely different APIs, and I am not sure if the **Splitting** parameter is available in the same way.

**Comment by wisetonny** [comment]
I verified the https://api-free.deepl.com/v2 support `"tag_handling": "html"` with a direct API call to the URL. (with other program language). It will return the correct result with HTML tags.

I assume https://www2.deepl.com supports it as well, but I didn't verify that.

**Comment by missuo** [comment]
You can Fork this project and modify it to try.

**Comment by wisetonny** [comment]
I just tried on the JS one: https://github.com/ifyour/deeplx. I make two lines of change, and it works.

1. Remove the splitting param.
2. Add tag_handling.

![Screenshot 2024-01-01 at 12 16 39 PM](https://github.com/OwO-Network/DeepLX/assets/18849626/dfee1fc5-6aba-4b0a-9224-3e730e18d876)

The translate result before the modify:

```html
<ul\n<li><strong>
```

After the modify:

```html
<ul> <li><strong>
```

Just a reference if you are willing to try it. Thanks.

**Comment by missuo** [comment]
I don't know how to add this feature, as it is a niche requirement. 

**Maybe I will add it in the next version, please stay tuned.**

**Comment by wijionejs** [comment]
Are there any plans to add this feature in the foreseeable future?
It would be awesome!

cc @missuo
