### ISSUE TITLE
How to pass below parameters to avoid block?  identifier, timestamp

### ISSUE THREAD

**Issue by nissansz** [OwO-Network/DeepLX#91]
https://github.com/ptrstn/deepl-translate/blob/ca61c63ff23031291fbaf220de92018fb85a57f0/deepl/hacks.py#L21-L22

 def generate_translation_request_data( 
     source_language, 
     target_language, 
     sentences, 
     identifier=MAGIC_NUMBER, 
     alternatives=1, 
     formality_tone=None, 
 ): 
     return { 
         "jsonrpc": "2.0", 
         "method": "LMT_handle_jobs", 
         "params": { 
             "jobs": generate_jobs(sentences, beams=alternatives), 
             "lang": { 
                 "user_preferred_langs": [target_language, source_language], 
                 "source_lang_computed": source_language, 
                 "target_lang": target_language, 
             }, 
             "priority": 1, 
             "commonJobParams": generate_common_job_params(formality_tone), 
             "timestamp": generate_timestamp(sentences), 
         }, 
         "id": identifier, 
     }

**Comment by missuo** [comment]
The code you sent is not from this repository.
