### ISSUE TITLE
[报错]

### ISSUE THREAD

**Issue by fgr178707** [OwO-Network/DeepLX#94]
2024/02/06 10:32:08 Post "https://www2.deepl.com/jsonrpc": dial tcp 172.65.212.243:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
![image](https://github.com/OwO-Network/DeepLX/assets/109357981/6ab6d9f8-21c0-482d-8e4b-8d86c8ca1c6b)

**Comment by missuo** [comment]
Please do not make frequent requests.

**Comment by fgr178707** [comment]
> Please do not make frequent requests.

I don't have the frequent requests. I've even just turned on my computer.

**Comment by fgr178707** [comment]
> Please do not make frequent requests.

No, it's fine.
