### ISSUE TITLE
[error]: 5次重试后依然出错:response.text='',Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by xiankaiyao** [OwO-Network/DeepLX#96]
今天翻译第一个的时候正常，但是第二次就这样：
[error]: 5次重试后依然出错:response.text='',Expecting value: line 1 column 1 (char 0)

**Comment by missuo** [comment]
Obviously, this error does not come from DeepLX. Please provide the error from DeepLX, as I cannot make judgments on errors from any other clients.
